version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    container_name: marche_kora_db
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: marche_kora
      POSTGRES_PASSWORD: kora_secret_2024
      POSTGRES_DB: marche_kora_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: marche_kora_pgadmin
    restart: unless-stopped
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@marchekora.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    depends_on:
      - postgres

volumes:
  postgres_data:
